# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto Crawler

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0,3,6,9,12,15 * * *'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-chromedriver: true
        install-dependencies: true
      run: |
        echo "Chromedriver Path: ${{ steps.setup-chrome.outputs.chromedriver-path }}"
        echo "CHROMEDRIVER_PATH=${{ steps.setup-chrome.outputs.chromedriver-path }}" >> $GITHUB_ENV

    - name: Move ChromeDriver to New Location
      run: |
        mkdir -p $GITHUB_WORKSPACE/chromedriver-win64
        mv $CHROMEDRIVER_PATH $GITHUB_WORKSPACE/chromedriver-win64/chromedriver.exe
        echo "ChromeDriver moved to $GITHUB_WORKSPACE/chromedriver-win64/chromedriver.exe"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path "requirements.txt") { pip install -r .\requirements.txt }

    - name: Run Crawler
      run: |
        python danawa_crawler.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    - name: Commits
      run: |
        git config --local user.email "sty1393@gmail.com"
        git config --local user.name "Auto_Crawler_Bot"
        git add --all
        git commit -m "Bot - Auto Crawl | $(date -d '+9 hour' +'%Y-%m-%d %H:%M:%S')"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        
